### ISSUE TITLE
XT-002 - Hunter (Survival) - Only spams Wingclip and Doesnt do rotation on Heart 

### ISSUE THREAD

**Issue by GustafGSvensson** [darhanger/Ni-Profiles#3]
Fighting XT-002 (33293) "Ulduar Boss" -  Using Survival DarhangeR 

The issue I have is on the 2nd part of the boss where it spawns its own heart (ID 33329) -  The Rotation then proceeds to only use 53339 (Mongoose Bite) and Wingclip (2974) on heart using the debugger tool provided - /dardebug. 

I saw that the heart is in the ni.tables.whitelistedlosunits - but not really sure what this includes, just that I am not getting any dps done during the heart phase, just auto shoots, and same on Kologarns [32934] = "Right Arm", [32933] = "Left Arm", 

Otherwise top quality rotation with great dmg output!

**Comment by GustafGSvensson** [comment]
Works after removing lines in WhitelistedLoSUnits.lua ( Ni\addon\Core\Tables)
Changed it to ni.tables.whitelistedlosunits = {}

**Comment by darhanger** [comment]
Seems its problem with nhub and white list. Its now with my stuff.
