### ISSUE TITLE
Bloodsurge Warrior Fury - 3.3.5

### ISSUE THREAD

**Issue by lucas3820** [darhanger/Ni-Profiles#4]
I performed the test checking the skill priority level, which skills the bot gave as a priority. When execute is enabled for example, it ignores slam (instant cast) which I think is imprudent, because slam I have no anger cost, so I have more dps for being more angry. However, if the developer tests and sees that DPS is higher this way, then that's fine. 

> Do you have plans for creating pvp combat routines? I have a suggestion to create Warrior tank pvp, please ^^ (3.3.5)

**Comment by darhanger** [comment]
Im never make PvP profile. Sorry.
