### ISSUE TITLE
Take priorities error.

### ISSUE THREAD

**Issue by lucas3820** [darhanger/Ni-Profiles#5]
In my opinion, there is an error in the priority of the execution of the abilities.
As I think it should be:
1 - Bloodthirst
2 - Whirlwind
3 - Slam! (spell = 46916)
4 - "Execute"
5 - Heroic Strike (When there is 50 rage or more) / Cleave (When there is 50 rage or more and more than one target, respecting the spell distance).

**Comment by darhanger** [comment]
Change it in future update.
