### ISSUE TITLE
About Warrior Fury rotation priority

### ISSUE THREAD

**Issue by lucas3820** [darhanger/Ni-Profiles#6]
The sequence of priorities in the Warrior Fury rotation is:

**1 - Bloodthirst**
**2 - Whirlwind**
**3 - Slam** (Buff)
**4 - Execute** (It remains in that same priority even the target with less than 20% health.)
**5 - Heroic Strike** (only against a target) 
**6 - Cleave** (When more than one target exists)

Tell me if I am wrong, in your rotation the execution is as top priority (among those spells I mentioned). I realized it well in inpirical tests.

**Comment by darhanger** [comment]
So. Why you keep spamming same issue?  I put it in to-do list → https://github.com/darhanger/Ni-Profiles/issues/5 .

Also im change queue
`local queue = {
	"Window",
	"Universal pause",
	"AutoTarget",
	"Berserker Stance",
	"Battle Shout",
	"Enraged Regeneration",
	"Berserker Rage",
	"Combat specific Pause",
	"Healthstone (Use)",
	"Potions (Use)",
	"Racial Stuff",
	"Use enginer gloves",
	"Trinkets",
	"Pummel (Interrupt)",
	"Death Wish",
	"Recklessness",
	"Bloodrage",
	"Victory Rush",
	"Bloodthirst",
	"Whirlwind",
	"Slam",
	"Execute",
	"Heroic Strike + Cleave (Filler)",
}`

And Heroic Strike and Cleave work same like you wanna even in old rotation. 
`	["Heroic Strike + Cleave (Filler)"] = function()
		if IsSpellInRange(GetSpellInfo(47475), "target") == 1  -- range check
		 and ni.player.power() > 45 then -- Rage more then 45
			if ActiveEnemies() >= 1	   -- if more then one target 
			 and ni.spell.available(47520, true) 
			 and not IsCurrentSpell(47520) then
				ni.spell.cast(47520, "target") -- cast Cleave
			return true
		else
			if ActiveEnemies() == 0 -- one target 
			 and ni.spell.available(47450, true)
			 and not IsCurrentSpell(47450) then
				ni.spell.cast(47450, "target") -- cast Heroic Strike
			return true
				end
			end
		end
	end,`
