### ISSUE TITLE
Consecration spell in protection paladin rotation doesn't check the range properly.

### ISSUE THREAD

**Issue by V3semir** [darhanger/Ni-Profiles#7]
Range validation of Consecration spell in paladin protection rotation is set to Crusader Strike instead of Hammer of the Righteous.
`	["Consecration"] = function()
		local _, enabled = GetSetting("concentrat")
		local value = GetSetting("concentratmana") 
        if enabled
		 and ni.player.power() > value
		 and ni.spell.isinstant(48819)
		 and ni.spell.available(48819)
		 and ni.spell.valid("target", 35395) then
			ni.spell.cast(48819, "target")
			return true
		end
	end,`

Should be:
`	["Consecration"] = function()
		local _, enabled = GetSetting("concentrat")
		local value = GetSetting("concentratmana") 
        if enabled
		 and ni.player.power() > value
		 and ni.spell.isinstant(48819)
		 and ni.spell.available(48819)
		 and ni.spell.valid("target", 53595) then
			ni.spell.cast(48819, "target")
			return true
		end
	end,`

**Comment by darhanger** [comment]
Fixed.
